version: '3.1'

services:

  db:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_DB: youtube_db
    ports:
      - 5433:5432

  client:
    build: ./client
    restart: always
    ports:
      - 8000:8000
  
  server:
    build: ./server
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
  
  cron:
    build: ./server
    command: ./cron.sh
    restart: always
    depends_on:
      - server