"""empty message

Revision ID: b2aa11f12c5e
Revises: 86e1fe3bcbe0
Create Date: 2018-09-27 03:15:48.361333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2aa11f12c5e'
down_revision = '86e1fe3bcbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('hide_time', sa.DateTime(), nullable=False))
    op.add_column('videos', sa.Column('show_time', sa.DateTime(), nullable=False))
    op.alter_column('videos', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('videos', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('videos', 'show_time')
    op.drop_column('videos', 'hide_time')
    # ### end Alembic commands ###
