"""empty message

Revision ID: e765150daa47
Revises: b2aa11f12c5e
Create Date: 2018-09-30 01:00:27.611820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e765150daa47'
down_revision = 'b2aa11f12c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumb', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumb')
    # ### end Alembic commands ###
